# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixfmt"
options = ["--width=100"]
includes = ["*.nix"]
# Exclude files that nixfmt doesn't handle well
excludes = ["modules/editors/neovim/default.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md"]

[formatter.fish]
command = "fish_indent"
options = ["--write"]
# Scripts don't have extensions, so we have to list them one by one
# See numtide/treefmt#33 for more info
includes = [
    "*.fish",
    "bin/,",
    "bin/git-peek",
    "bin/mount-backup",
    "bin/show",
    "bin/sysdo",
]

[formatter.lua]
command = "lua-format"
options = ["-i"]
includes = ["*.lua"]
