name: "Build flake outputs"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        output:
          - devShell.x86_64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - name: Cleanup disk
        uses: curoky/cleanup-disk-action@v2.0
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Configure Cachix
        uses: cachix/cachix-action@v11
        with:
          name: i077
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build flake output
        run: nix build -v .#${{ matrix.output }}

        # These next steps calculate the diff between the old and new closures for a flakebot PR,
        # and posts the result for each host in a comment.
      - name: Calculate diff between closures
        # Only run if we're in a flakebot PR
        if: ${{ github.event_name == 'pull_request' && github.head_ref == 'flakebot' }}
        run: |
          nix build -v .#${{ matrix.output }} -o result-new
          nix build -v .\?ref=$(git rev-parse @~)#${{ matrix.output }} -o result-old
          echo "diff_closure<<EOF" >> $GITHUB_ENV
          # TODO remove pipe to sed when NixOS/nix#4626 is fixed
          nix store diff-closures ./result-old ./result-new | sed 's/\x1b\[[0-9;]*m//g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post diff to PR comment
        if: ${{ github.event_name == 'pull_request' && github.head_ref == 'flakebot' }}
        uses: phulsechinmay/rewritable-pr-comment@v0.3.0
        with:
          message: |
            ### Closure diff for `${{ matrix.output }}`
            ```
            ${{ env.diff_closure }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: closure-diff-${{ matrix.output }}
