name: "Build and cache NixOS configurations"
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hostname: [giratina, dialga]
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Configure Cachix
        uses: cachix/cachix-action@v8
        with:
          name: i077
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build configuration
        run: nix build -v .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel
