name: "Build rescue image"
on:
  push:
    branches:
      - master
    paths:
      - flake.lock
      - flake/rescue.nix
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-linux
    steps:
      - uses: actions/checkout@v4
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v14
        with:
          name: i077
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build rescue image
        run: nix build --accept-flake-config .#packages.${{ matrix.arch }}.rescueImage
      - uses: actions/upload-artifact@v4
        with:
          name: rescue-image
          path: result/iso/*.iso
          retention-days: 7
