name: "Build rescue image"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Configure Cachix
        uses: cachix/cachix-action@v12
        with:
          name: i077
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build rescue image
        run: nix build --accept-flake-config .#packages.${{ matrix.arch }}.rescueImage
      - uses: actions/upload-artifact@v3
        with:
          name: rescue-image
          path: result/iso/*.iso
          retention-days: 7
