name: Update flake inputs

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches: 
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: cachix/install-nix-action@v15
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Prepare flakebot branch
      run: |
        git config --local user.email "flakebot@users.noreply.github.com"
        git config --local user.name "flakebot"
        git checkout -B flakebot
    - name: Update & commit lockfile
      run: |
        nix flake update --commit-lock-file
        echo "commit_info<<EOF" >> $GITHUB_ENV
        git log --format=%B -1 >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.FLAKEBOT_PR_TOKEN }}
        branch: flakebot
        force: true
    - name: pull-request-action
      uses: vsoch/pull-request-action@1.0.18
      env:
        GITHUB_TOKEN: ${{ secrets.FLAKEBOT_PR_TOKEN }}
        PULL_REQUEST_FROM_BRANCH: flakebot
        PULL_REQUEST_BRANCH: master
        PULL_REQUEST_UPDATE: true
        MAINTAINER_CANT_MODIFY: true
        PASS_ON_ERROR: true
        PULL_REQUEST_TITLE: Update flake inputs
        PULL_REQUEST_BODY: |
          This is an automated pull request to update this flake's inputs.
          ```
          ${{ env.commit_info }}
          ```
