name: Update flake inputs

on:
  schedule:
    - cron: "0 4 * * 2,5"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@v20
      with:
        token: ${{ secrets.GH_UPDATER_TOKEN }}
        nix-options: --accept-flake-config
        pr-body: |
          Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

          ```
          {{ env.GIT_COMMIT_MESSAGE }}
          ```
